/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlct;

/**
 *
 * @author lozim
 */
public class Itemgiaodichganday extends javax.swing.JPanel {

public void setThongTin(String ten, String tien, String ngay) {
    lblTen.setText(ten);      // Thay jLabel2 bằng lTen
    lblSoTien.setText(tien);  // Thay jLabel4 bằng lSoTien
    lblNgay.setText(ngay);    // Thay jLabel3 bằng lNgay
}
    /**
     * Creates new form Itemgiaodichganday
     */
    public Itemgiaodichganday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblSoTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("icon");

        lblTen.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTen.setText("Tên danh mục");

        lblNgay.setForeground(new java.awt.Color(102, 102, 102));
        lblNgay.setText("Thứ ngày tháng");

        lblSoTien.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblSoTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoTien.setText("số tiền");
        lblSoTien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTen)
                    .addComponent(lblSoTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgay)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblSoTien;
    private javax.swing.JLabel lblTen;
    // End of variables declaration//GEN-END:variables
}
