package com.mycompany.qlct;

import java.time.YearMonth;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author lozim
 */
public class MainFrame extends javax.swing.JFrame {

    private PanelThemGiaoDich bottomSheet;
    private PanelSoGiaoDich pnlSGD;
    private javax.swing.Timer slideUpTimer;
    private javax.swing.Timer slideDownTimer;
    private boolean isSheetUp = false; // Biến kiểm tra xem bảng đang bật hay tắt

    private GiaoDichController_Moi gdController; // Cầu nối xử lý logic Giao Dịch

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        // 1. Ép cứng kích thước chuẩn của điện thoại (rộng 450, cao 750)
        this.setSize(450, 750);
        // 2. Cấm người dùng dùng chuột kéo viền phóng to/thu nhỏ
        this.setResizable(false);
        // 3. Cho app luôn hiện ra ngay chính giữa màn hình máy tính
        this.setLocationRelativeTo(null);

        // Khởi tạo bảng trượt
        bottomSheet = new PanelThemGiaoDich();
        bottomSheet.setSize(450, 700);
        bottomSheet.setLocation(0, 750);
        this.getLayeredPane().add(bottomSheet, javax.swing.JLayeredPane.POPUP_LAYER);

        // ---- KHỞI TẠO SỔ GIAO DỊCH VÀ CONTROLLER ĐÚNG 1 LẦN DUY NHẤT TẠI ĐÂY ----
        pnlSGD = new PanelSoGiaoDich();
        DialogSuaGiaoDich dialogSua = new DialogSuaGiaoDich(this, true);
        gdController = new GiaoDichController_Moi(pnlSGD, bottomSheet, dialogSua, "ND01");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelBottomMeunu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        PanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBottomMeunu.setPreferredSize(new java.awt.Dimension(576, 60));
        PanelBottomMeunu.setRequestFocusEnabled(false);
        PanelBottomMeunu.setLayout(new java.awt.GridLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButton1.setText("Tổng quan");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PanelBottomMeunu.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButton2.setText("Giao dịch");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        PanelBottomMeunu.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        PanelBottomMeunu.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButton4.setText("Ngân sách");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        PanelBottomMeunu.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButton5.setText("Heo đất");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        PanelBottomMeunu.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButton6.setText("Tài khoản");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        PanelBottomMeunu.add(jButton6);

        getContentPane().add(PanelBottomMeunu, java.awt.BorderLayout.SOUTH);

        PanelContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelContentLayout = new javax.swing.GroupLayout(PanelContent);
        PanelContent.setLayout(PanelContentLayout);
        PanelContentLayout.setHorizontalGroup(
                PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 576, Short.MAX_VALUE)
        );
        PanelContentLayout.setVerticalGroup(
                PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(PanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        PanelContent.removeAll();
        PanelNganSach pnlNS = new PanelNganSach();
        pnlNS.setSize(PanelContent.getSize());
        PanelContent.add(pnlNS);
        PanelContent.revalidate();
        PanelContent.repaint();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        PanelContent.removeAll();
        PanelTongquan pnlTQ = new PanelTongquan();
        pnlTQ.setSize(PanelContent.getSize());
        PanelContent.add(pnlTQ);
        PanelContent.revalidate();
        PanelContent.repaint();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        PanelContent.removeAll();

        // Tái sử dụng đối tượng pnlSGD duy nhất, ép kích thước vừa vặn
        if (pnlSGD != null) {
            pnlSGD.setSize(PanelContent.getSize());
            PanelContent.add(pnlSGD);

            // Gọi Controller cập nhật lại số liệu chính xác theo đúng tháng hiện tại của panel đó
            if (gdController != null) {
                gdController.loadDuLieuTheoThang();
            }
        }

        PanelContent.revalidate();
        PanelContent.repaint();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        PanelContent.removeAll();
        PanelHeoDat pnlHD = new PanelHeoDat();
        pnlHD.setSize(PanelContent.getSize());
        PanelContent.add(pnlHD);
        PanelContent.revalidate();
        PanelContent.repaint();
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        PanelContent.removeAll();
        PanelTaiKhoan pnlTK = new PanelTaiKhoan();
        pnlTK.setSize(PanelContent.getSize());
        PanelContent.add(pnlTK);
        PanelContent.revalidate();
        PanelContent.repaint();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        if (bottomSheet != null) {
            int targetY = this.getHeight() - bottomSheet.getHeight() - 40;
            if (targetY < 0) {
                targetY = 100;
            }
            bottomSheet.setLocation(0, targetY);
            bottomSheet.setVisible(true);
        }

        javax.swing.SwingUtilities.invokeLater(() -> {
            if (gdController != null) {
                gdController.loadDanhMucToComboBox();
            }
            if (bottomSheet != null) {
                bottomSheet.revalidate();
                bottomSheet.repaint();
            }
        });
    }

    public void closeBottomSheet() {
        if (bottomSheet != null) {
            bottomSheet.setLocation(0, 750);
            bottomSheet.setVisible(false);

            this.getLayeredPane().revalidate();
            this.getLayeredPane().repaint();
        }
    }

    public javax.swing.JPanel getBottomSheet() {
        return bottomSheet;
    }

    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel PanelBottomMeunu;
    private javax.swing.JPanel PanelContent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration                     
}
