/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlct;

/**
 *
 * @author lozim
 */
public class PanelTongquan extends javax.swing.JPanel {

    /**
     * Creates new form PanelTongquan
     */
    public PanelTongquan() {
        initComponents();
        veDoThiDuong("CHI");
        chonTab("CHI"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblThu = new javax.swing.JLabel();
        lblSoTienThu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblChi = new javax.swing.JLabel();
        lblSoTienChi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlDoThi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        itemgiaodichganday2 = new com.mycompany.qlct.Itemgiaodichganday();
        itemgiaodichganday3 = new com.mycompany.qlct.Itemgiaodichganday();
        itemgiaodichganday4 = new com.mycompany.qlct.Itemgiaodichganday();
        itemgiaodichganday5 = new com.mycompany.qlct.Itemgiaodichganday();
        itemgiaodichganday6 = new com.mycompany.qlct.Itemgiaodichganday();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblThu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblThu.setText("TỔNG THU");
        lblThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuMouseClicked(evt);
            }
        });

        lblSoTienThu.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        lblSoTienThu.setForeground(new java.awt.Color(51, 153, 0));
        lblSoTienThu.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("đ");

        lblChi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblChi.setText("TỔNG CHI");
        lblChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChiMouseClicked(evt);
            }
        });

        lblSoTienChi.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        lblSoTienChi.setForeground(new java.awt.Color(204, 0, 0));
        lblSoTienChi.setText("jLabel5");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("đ");

        jPanel2.setBackground(new java.awt.Color(255, 235, 11));
        jPanel2.setForeground(new java.awt.Color(255, 225, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SỐ DƯ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("VND");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14))
        );

        pnlDoThi.setBackground(new java.awt.Color(238, 238, 238));
        pnlDoThi.setMaximumSize(new java.awt.Dimension(400, 200));
        pnlDoThi.setMinimumSize(new java.awt.Dimension(400, 200));
        pnlDoThi.setOpaque(false);
        pnlDoThi.setPreferredSize(new java.awt.Dimension(400, 200));

        javax.swing.GroupLayout pnlDoThiLayout = new javax.swing.GroupLayout(pnlDoThi);
        pnlDoThi.setLayout(pnlDoThiLayout);
        pnlDoThiLayout.setHorizontalGroup(
            pnlDoThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDoThiLayout.setVerticalGroup(
            pnlDoThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Giao dịch gần đây");

        jPanel6.setBackground(new java.awt.Color(239, 255, 235));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        itemgiaodichganday2.setBackground(new java.awt.Color(241, 255, 241));
        jPanel6.add(itemgiaodichganday2);

        itemgiaodichganday3.setBackground(new java.awt.Color(241, 255, 241));
        jPanel6.add(itemgiaodichganday3);

        itemgiaodichganday4.setBackground(new java.awt.Color(241, 255, 241));
        jPanel6.add(itemgiaodichganday4);

        itemgiaodichganday5.setBackground(new java.awt.Color(241, 255, 241));
        jPanel6.add(itemgiaodichganday5);

        itemgiaodichganday6.setBackground(new java.awt.Color(241, 255, 241));
        jPanel6.add(itemgiaodichganday6);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 153, 0));
        jButton1.setText("Xem tất cả");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSoTienChi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lblSoTienThu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(lblThu))))
                    .addComponent(pnlDoThi, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(346, 346, 346)
                            .addComponent(jButton1))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChi)
                    .addComponent(lblThu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoTienChi)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoTienThu)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(pnlDoThi, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // 1. Tạo ra một trang Số giao dịch mới
        PanelSoGiaoDich trangGiaoDich = new PanelSoGiaoDich();

        // 2. Lấy cái khung cửa sổ chính (MainFrame) đang chứa mọi thứ
        javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 3. Lột bỏ giao diện hiện tại
        frame.getContentPane().removeAll();

        // 4. Lắp trang Số giao dịch vào khung
        frame.getContentPane().add(trangGiaoDich);

        // 5. Cập nhật và vẽ lại màn hình mới
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_jButton1MouseClicked

    private void lblChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChiMouseClicked
        veDoThiDuong("CHI");
        chonTab("CHI");
    }//GEN-LAST:event_lblChiMouseClicked

    private void lblThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuMouseClicked
        veDoThiDuong("THU");
        chonTab("THU");
    }//GEN-LAST:event_lblThuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.qlct.Itemgiaodichganday itemgiaodichganday2;
    private com.mycompany.qlct.Itemgiaodichganday itemgiaodichganday3;
    private com.mycompany.qlct.Itemgiaodichganday itemgiaodichganday4;
    private com.mycompany.qlct.Itemgiaodichganday itemgiaodichganday5;
    private com.mycompany.qlct.Itemgiaodichganday itemgiaodichganday6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChi;
    private javax.swing.JLabel lblSoTienChi;
    private javax.swing.JLabel lblSoTienThu;
    private javax.swing.JLabel lblThu;
    private javax.swing.JPanel pnlDoThi;
    // End of variables declaration//GEN-END:variables
// Sửa hàm vẽ đồ thị để đơn giản hóa giao diện

// Sửa hàm vẽ đồ thị để đơn giản hóa giao diện
    private void veDoThiDuong(String loaiGiaoDich) {
        // 1. Chuẩn bị bộ dữ liệu (giữ nguyên dữ liệu)
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
        java.awt.Color mauDoThi;

        if (loaiGiaoDich.equals("CHI")) {
            dataset.addValue(0, "Chi", "01/06");
            dataset.addValue(1000000, "Chi", "10/06");
            dataset.addValue(1824000, "Chi", "20/06");
            dataset.addValue(1824000, "Chi", "30/06");
            mauDoThi = new java.awt.Color(255, 100, 100, 150); // Đỏ bán trong suốt
        } else {
            dataset.addValue(1000000, "Thu", "01/06");
            dataset.addValue(3000000, "Thu", "15/06");
            dataset.addValue(6000000, "Thu", "30/06");
            mauDoThi = new java.awt.Color(100, 200, 100, 150); // Xanh lá bán trong suốt
        }

// Dùng createLineChart thay vì createAreaChart
org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createLineChart(
        "", "", "", dataset, 
        org.jfree.chart.plot.PlotOrientation.VERTICAL, 
        false, true, false);

// Sau đó chỉnh độ dày của đường line:
        // 3. Trang điểm cho đồ thị ĐƠN GIẢN hóa tối đa
    org.jfree.chart.plot.CategoryPlot plot = chart.getCategoryPlot();
    
    // Đặt Renderer cho Line Chart
    org.jfree.chart.renderer.category.LineAndShapeRenderer renderer = new org.jfree.chart.renderer.category.LineAndShapeRenderer();
    plot.setRenderer(renderer); // Phải set renderer này vào plot trước
    renderer.setSeriesStroke(0, new java.awt.BasicStroke(3.0f)); // Độ dày đường kẻ
    renderer.setSeriesShapesVisible(0, false); // Ẩn các dấu chấm tại điểm dữ liệu cho đẹp
   
    org.jfree.chart.axis.CategoryAxis domainAxis = plot.getDomainAxis();
domainAxis.setTickLabelsVisible(true); // BẬT hiển thị ngày tháng
domainAxis.setTickLabelFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10)); // Font chữ nhỏ cho gọn
domainAxis.setTickLabelPaint(java.awt.Color.GRAY); // Màu chữ xám cho thanh thoát
domainAxis.setAxisLineVisible(true); // Hiển thị đường kẻ ngang ở dưới
        // Nền trắng tinh khôi
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        chart.setBackgroundPaint(java.awt.Color.WHITE);
        
        // Xóa TẤT CẢ các lưới mờ và viền
        plot.setDomainGridlinesVisible(false);
        plot.setRangeGridlinesVisible(false);
        plot.setOutlineVisible(false); // Xóa viền vuông bao quanh đồ thị

        // Đơn giản hóa trục TỪNG (DomainAxis)
        plot.getDomainAxis().setTickLabelsVisible(false); // Ẩn hoàn toàn các ngày tháng (01/06, 10/06...)
        plot.getDomainAxis().setAxisLineVisible(false); // Ẩn đường trục bên dưới

        // Đơn giản hóa trục Y (RangeAxis - trục tiền)
        org.jfree.chart.axis.NumberAxis rangeAxis = (org.jfree.chart.axis.NumberAxis) plot.getRangeAxis();
        rangeAxis.setAxisLineVisible(false); // Ẩn đường trục bên trái
        
        // Đặt khoảng tick cho trục Y để hiển thị ít nhãn hơn
        rangeAxis.setTickUnit(new org.jfree.chart.axis.NumberTickUnit(500000)); // Hiển thị nhãn mỗi 500,000 VND

        // 4. Cập nhật vào khung Panel [pnlDoThi]
        org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);
        pnlDoThi.removeAll();
        pnlDoThi.setLayout(new java.awt.BorderLayout());
        pnlDoThi.add(chartPanel, java.awt.BorderLayout.CENTER);
        pnlDoThi.validate();
        pnlDoThi.repaint();
    } 

    private void chonTab(String loaiTab) {
        // Tạo sẵn 3 loại viền gạch chân
        javax.swing.border.Border gachChanDo = javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 80, 80));
        javax.swing.border.Border gachChanXanh = javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(50, 200, 50));
        javax.swing.border.Border khongGachChan = javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0);

        // Bật/tắt hiệu ứng tùy theo tab được chọn
        if (loaiTab.equals("CHI")) {
            lblSoTienChi.setBorder(gachChanDo);
            lblSoTienThu.setBorder(khongGachChan);
            lblChi.setForeground(java.awt.Color.BLACK);
            lblThu.setForeground(java.awt.Color.GRAY);
        } else {
            lblSoTienThu.setBorder(gachChanXanh);
            lblSoTienChi.setBorder(khongGachChan);
            lblThu.setForeground(java.awt.Color.BLACK);
            lblChi.setForeground(java.awt.Color.GRAY);
        }
    }
}

