/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlct;

/**
 *
 * @author lozim
 */
public class PanelSoGiaoDich extends javax.swing.JPanel {
// Biến lưu trữ tháng và năm hiện tại

    private java.time.YearMonth thangHienTai = java.time.YearMonth.now();

    /**
     * Creates new form PanelSoGiaoDich
     */
    private javax.swing.JTextField txtTimKiem;

    public PanelSoGiaoDich() {
        initComponents();
        styleNutPhang(btnLui);
        styleNutPhang(btnTien);

        // ---- CHÈN Ô TÌM KIẾM THỦ CÔNG VÀO GIAO DIỆN ----
//        txtTimKiem = new javax.swing.JTextField();
//        txtTimKiem.setToolTipText("Nhập ghi chú hoặc tên danh mục để tìm kiếm...");
//        // Thiết kế khung viền bo nhẹ hoặc đơn giản cho hợp mắt
//        txtTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm nhanh"));
//
//        // Đưa ô tìm kiếm vào layout bên trên danh sách giao dịch
//        // Ta thêm nó vào trước jScrollPane1
//        this.add(txtTimKiem, 3); // Chèn vào vị trí thích hợp trong layout quản lý

        capNhatHienThi();
    }

    private void styleNutPhang(javax.swing.JButton btn) {
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setForeground(java.awt.Color.GRAY);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setForeground(java.awt.Color.BLACK);
            }
        });
    }

    private void capNhatHienThi() {
        String thangNam = "Tháng " + thangHienTai.getMonthValue() + ", " + thangHienTai.getYear();
        lblThangHienTai.setText(thangNam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLui = new javax.swing.JButton();
        lblThangHienTai = new javax.swing.JLabel();
        btnTien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlDanhSach = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        btnLui.setText("<");
        btnLui.addActionListener(this::btnLuiActionPerformed);
        jPanel1.add(btnLui);

        lblThangHienTai.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblThangHienTai.setText("tháng/năm");
        jPanel1.add(lblThangHienTai);

        btnTien.setText(">");
        btnTien.addActionListener(this::btnTienActionPerformed);
        jPanel1.add(btnTien);

        jPanel2.setBackground(new java.awt.Color(255, 255, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tổng thu ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tổng chi ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số dư");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("jLabel4");

        jLabel7.setText("đ");

        jLabel8.setText("đ");

        jLabel9.setText("đ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Giao dịch trong tháng");

        pnlDanhSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSach.setLayout(new javax.swing.BoxLayout(pnlDanhSach, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlDanhSach);

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuiActionPerformed
        thangHienTai = thangHienTai.minusMonths(1); // Lùi 1 tháng
        capNhatHienThi();
//        themDanhSachGiaoDich();
    }//GEN-LAST:event_btnLuiActionPerformed

    private void btnTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienActionPerformed
        thangHienTai = thangHienTai.plusMonths(1); // Tiến 1 tháng
        capNhatHienThi();
//        themDanhSachGiaoDich();
    }//GEN-LAST:event_btnTienActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLui;
    private javax.swing.JButton btnTien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThangHienTai;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
// ================= GETTERS CHO PANEL SỔ GIAO DỊCH =================
    public javax.swing.JButton getBtnLui() {
        return btnLui;
    }

    public javax.swing.JButton getBtnTien() {
        return btnTien;
    }

    public javax.swing.JLabel getLblTongThu() {
        return jLabel4;
    }

    public javax.swing.JLabel getLblTongChi() {
        return jLabel5;
    }

    public javax.swing.JLabel getLblSoDu() {
        return jLabel6;
    }

    public java.time.YearMonth getThangHienTai() {
        return thangHienTai;
    }
    public javax.swing.JTextField getTxtTimKiem() {
        return txtSearch;
    }

    // ================= TẠO CALLBACK CLICK CHUỘT =================
    public interface OnGiaoDichClickListener {

        void onClick(Object[] rowData);
    }
    private OnGiaoDichClickListener clickListener;

    public void setOnGiaoDichClickListener(OnGiaoDichClickListener listener) {
        this.clickListener = listener;
    }

    // ================= HÀM VẼ DANH SÁCH GIAO DỊCH LÊN MÀN HÌNH =================
    // Hàm này thay thế hoàn toàn cho hàm themDanhSachGiaoDich() cũ để nhận dữ liệu thật từ Controller
    public void renderDanhSachGiaoDich(java.util.List<Object[]> listGD) {
        pnlDanhSach.removeAll();

        for (Object[] row : listGD) {
            Itemgiaodichganday item = new Itemgiaodichganday();

            // Index: 0-MaGD, 1-Tien, 2-GhiChu, 3-TenDM, 4-ThoiGian
            String tenDM_GhiChu = row[3].toString() + " (" + row[2].toString() + ")";
            String soTien = String.format("%,.0f đ", (Double) row[1]);

            java.sql.Timestamp ts = (java.sql.Timestamp) row[4];
            String ngayThang = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm").format(ts);

            item.setThongTin(tenDM_GhiChu, soTien, ngayThang);

            item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            item.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    if (clickListener != null) {
                        clickListener.onClick(row);
                    }
                }
            });

            pnlDanhSach.add(item);
        }

        pnlDanhSach.revalidate();
        pnlDanhSach.repaint();
    }
}
